### ISSUE TITLE
Handling StringTie .gtf files

### ISSUE THREAD

**Issue by JPFinnigan** [hammerlab/topiary#39]
Hey Guys,

I'm trying to re-run Topiary wit the RNASeq data we just generated, but I'm experiencing an issue related to compatibility w/ the StringTie output .gtf/.gff. I was under the impression that .gtf files were supported but if that isn't the case please ignore the remainder of this bug report. 

Command line arg: 
```
python /Library/Frameworks/Python.framework/Versions/2.7/bin/topiary \
--vcf ~/Desktop/TEMP/Results/WES/Tumor_B16_F1_0821/ISMMS/VCF/MuTect/Tumor_B16_F1_0821.mutect.targets.pass.vcf \
--mhc-predictor netmhcpan \
--mhc-alleles H2-Kb,H2-Db \
--ic50-cutoff 500 \
--mhc-epitope-lengths 8,9,10,11 \
--rna-transcript-fpkm-file ~/Desktop/TEMP/Results/RNA/Tumor_B16.F1/ISMMS/Tumor_B16.F1_0821.115B/GTF/Tumor_B16.F1_0821.115B.stringtie.sorted.gtf \
--rna-min-transcript-expression 0.1 \
--output-csv ~/Desktop/test.csv
```
Output:
```
Topiary commandline arguments:
Namespace(ic50_cutoff=500.0, json_variant_files=[], maf=[], mhc_alleles='H2-Kb,H2-Db', mhc_alleles_file=None, mhc_epitope_lengths=[8, 9, 10, 11], mhc_predictor='netmhcpan', only_novel_epitopes=False, output_csv='/Users/johnfinnigan/Desktop/test.csv', output_html=None, padding_around_mutation=None, percentile_cutoff=None, reference_name=None, rna_gene_fpkm_file='/Users/johnfinnigan/Desktop/TEMP/Results/RNA/Tumor_B16.F1/ISMMS/Tumor_B16.F1_0821.115B/GTF/Tumor_B16.F1_0821.115B.stringtie.sorted.gtf', rna_min_gene_expression=0.1, rna_min_transcript_expression=0.0, rna_transcript_fpkm_file=None, skip_variant_errors=False, variant=[], vcf=['/Users/johnfinnigan/Desktop/TEMP/Results/WES/Tumor_B16_F1_0821/ISMMS/VCF/MuTect/Tumor_B16_F1_0821.mutect.targets.pass.vcf'], wildtype_ligandome_directory=None)
INFO:root:Building MHC binding prediction type for alleles ['H-2-Kb', 'H-2-Db'] and epitope lengths [8, 9, 10, 11]
INFO:root:Skipping allele SLA-1-CHANGDA: Malformed MHC type 1
INFO:root:Skipping allele SLA-1-HB01: Malformed MHC type 1
INFO:root:Skipping allele SLA-1-HB02: Malformed MHC type 1
INFO:root:Skipping allele SLA-1-HB03: Malformed MHC type 1
INFO:root:Skipping allele SLA-1-HB04: Malformed MHC type 1
INFO:root:Skipping allele SLA-1-LWH: Malformed MHC type 1
INFO:root:Skipping allele SLA-1-TPK: Malformed MHC type 1
INFO:root:Skipping allele SLA-1-YC: Malformed MHC type 1
INFO:root:Skipping allele SLA-1-YDL01: Malformed MHC type 1
INFO:root:Skipping allele SLA-1-YTH: Malformed MHC type 1
INFO:root:Skipping allele SLA-2-YDL02: Malformed MHC type 2
INFO:root:Skipping allele SLA-3-CDY: Malformed MHC type 3
INFO:root:Skipping allele SLA-3-HB01: Malformed MHC type 3
INFO:root:Skipping allele SLA-3-LWH: Malformed MHC type 3
INFO:root:Skipping allele SLA-3-TPK: Malformed MHC type 3
INFO:root:Skipping allele SLA-3-YC: Malformed MHC type 3
INFO:root:Skipping allele SLA-3-YDL: Malformed MHC type 3
INFO:root:Skipping allele SLA-3-YDY01: Malformed MHC type 3
INFO:root:Skipping allele SLA-3-YDY02: Malformed MHC type 3
INFO:root:Skipping allele SLA-3-YTH: Malformed MHC type 3
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/topiary", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/johnfinnigan/Desktop/Utilities/Topiary/topiary/scripts/topiary", line 64, in <module>
    main()
  File "/Users/johnfinnigan/Desktop/Utilities/Topiary/topiary/scripts/topiary", line 46, in main
    epitopes = predict_epitopes_from_args(args)
  File "/Users/johnfinnigan/Desktop/Utilities/Topiary/topiary/topiary/predict_epitopes.py", line 277, in predict_epitopes_from_args
    gene_expression_dict = rna_gene_expression_dict_from_args(args)
  File "/Users/johnfinnigan/Desktop/Utilities/Topiary/topiary/topiary/commandline_args.py", line 270, in rna_gene_expression_dict_from_args
    return load_cufflinks_fpkm_dict(args.rna_gene_fpkm_file)
  File "/Users/johnfinnigan/Desktop/Utilities/Topiary/topiary/topiary/rna/cufflinks.py", line 243, in load_cufflinks_fpkm_dict
    in load_cufflinks_dataframe(*args, **kwargs).iterrows()
  File "/Users/johnfinnigan/Desktop/Utilities/Topiary/topiary/topiary/rna/cufflinks.py", line 134, in load_cufflinks_dataframe
    check_required_columns(df, filename, required_columns)
  File "/Users/johnfinnigan/Desktop/Utilities/Topiary/topiary/topiary/rna/common.py", line 58, in check_required_columns
    column_name))
ValueError: FPKM tracking file /Users/johnfinnigan/Desktop/TEMP/Results/RNA/Tumor_B16.F1/ISMMS/Tumor_B16.F1_0821.115B/GTF/Tumor_B16.F1_0821.115B.stringtie.sorted.gtf missing column 'tracking_id'
```

The column headers for the StringTie .gtf output are consistent w/ the Ensenbl .GTF v.2 standards (link: http://www.ensembl.org/info/website/upload/gff.html), but Topiary seems to require columns w/h are found in the output of cufflinks (e.g. 'tracking_id').

**Comment by iskandr** [comment]
@JPFinnigan Is this fixed for you?

**Comment by JPFinnigan** [comment]
Hey, 

Yeah #40 resolved the issue.

**Comment by iskandr** [comment]
Awesome. Any other outstanding problems?
