### ISSUE TITLE
self-ligandome filter fails when unusual alleles have epitopes

### ISSUE THREAD

**Issue by kippakers** [hammerlab/topiary#61]
Hi guys,

I know from #49 this isn't a priority, but for posterity and maybe it affects other processes, I wanna point out a bug.  I encountered this:
```
Traceback (most recent call last):
  File "/hpc/users/akersn01/.local/bin/topiary", line 64, in <module>
    main()
  File "/hpc/users/akersn01/.local/bin/topiary", line 46, in main
    epitopes = predict_epitopes_from_args(args)
  File "/hpc/users/akersn01/.local/lib/python2.7/site-packages/topiary/predict_epitopes.py", line 296, in predict_epitopes_from_args
    raise_on_variant_effect_error=not args.skip_variant_errors)
  File "/hpc/users/akersn01/.local/lib/python2.7/site-packages/topiary/predict_epitopes.py", line 263, in predict_epitopes_from_variants
    wildtype_ligandome_dict=wildtype_ligandome_dict)
  File "/hpc/users/akersn01/.local/lib/python2.7/site-packages/topiary/predict_epitopes.py", line 166, in predict_epitopes_from_mutation_effects
    wildtype_ligandome_dict=wildtype_ligandome_dict)
  File "/hpc/users/akersn01/.local/lib/python2.7/site-packages/topiary/epitope_prediction.py", line 138, in build_epitope_collection_from_binding_predictions
    peptide in wildtype_ligandome_dict[allele]
  File "/hpc/users/akersn01/.local/lib/python2.7/site-packages/topiary/lazy_ligandome_dict.py", line 56, in __getitem__
    raise AlleleNotFound(allele_name)
topiary.lazy_ligandome_dict.AlleleNotFound: HLA-A*02:264
```
Which is odd, because I have A02264 in my self-ligandome directory.  Same thing happened with HLA-A\*02:253 and HLA-C\*07:101.  I think the pattern is triple digits in the 2nd half of the allele ID.  Should I be naming my ligandome files differently?  

Thanks!

**Comment by iskandr** [comment]
Fixed by https://github.com/hammerlab/mhcnames/issues/5
