### ISSUE TITLE
Issue locating NetMHCpan

### ISSUE THREAD

**Issue by ARChakravarthy** [hammerlab/topiary#77]
Hi there, 

I am trying to call neoepitopes using a locally installed version of topiary and NetMHCpan, and keep running into this error 

> Traceback (most recent call last):
>   File "/usr/local/bin/topiary", line 58, in <module>
>     main(args)
>   File "/usr/local/bin/topiary", line 43, in main
>     epitopes = predict_epitopes_from_args(args)
>   File "/usr/local/lib/python2.7/dist-packages/topiary/predict_epitopes.py", line 273, in predict_epitopes_from_args
>     mhc_model = mhc_binding_predictor_from_args(args)
>   File "/usr/local/lib/python2.7/dist-packages/mhctools/cli/args.py", line 150, in mhc_binding_predictor_from_args
>     return mhc_class(**kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/mhctools/netmhc_pan.py", line 43, in NetMHCpan
>     stderr=devnull)
>   File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
>     raise CalledProcessError(retcode, cmd, output=output)
> subprocess.CalledProcessError: Command '['netMHCpan', '--version', '_MHCTOOLS_VERSION_SNIFFING']' returned non-zero exit status 1
> 

The netMHCpan install on my computer is version 3.0, and interestingly netMHCpan by itself has issues calling the version command internally (although I can do it externally using an echo command)

**Comment by ARChakravarthy** [comment]
I figured out there was an issue with my path to NetMHCpan
